languageCode = "en-us"
title = "Eduardo Pilla Portilho"
baseURL = "https://eduardoportilho.github.io/blog/"
author = "Eduardo Pilla Portilho"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "headshot_190.jpg"
  author = "Eduardo Pilla Portilho"
  description = "Describe your website"


  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "eduardoportilho"
  Email         = "eduardo@portilho.com"
  Twitter       = "eduardoportilho"
  LinkedIn      = "eduardoportilho"
  Stackoverflow = "827013"
  Spotify       = "12162522496"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
